---

- name: HPC Template
  gather_facts: no
  connection: local
  hosts: ucsm
  vars:
    - ucs_site_name: TestSite
    - ucs_site_dn: "org-root/org-{{ ucs_site_name }}"
    - ucs_site_description: Test Site for Ansible Demonstration
    - deployment_state: present
    - mac_pool_name: "{{ ucs_site_name }}"
    - ucs_bios_policy_name: "HPC"

  tasks:
  - name: "Create Site {{ ucs_site_name  }}"
    include_tasks: task-ConfigureSite.yaml

  - include_tasks: task-CreateSystemVLANs.yaml
    vars:
    # List of VLANS to be created on the Fabric Interconnects
    - vlans:
        { mgmtVlan: { id: "50", fabric: "common", native: "no", sharing: "none" }}
  
  # One VNIC Template for LINUX Host with failover
  - include_tasks: task-CreateVNIC.yaml
    vars:
    - vlans:
       -  { mgmtVlan: { native: "yes" }}
    - vnic_fabric: "A-B"
    - vnic_mtu: "1500"
    - vnic_name: "eth0"
    - vnic_redundancy_type: "none"
    - vnic_template_type: "updating-template"
    - vnic_org_dn: "{{ ucs_site_dn }}"
         
  # MAC Pool for VNICs
  - include_tasks: task-CreateMACAddressPool.yaml
    vars:
    - map_name: "{{ ucs_site_name }}"
    - map_first_addr: "00:25:B5:02:00:00"
    - map_last_addr: "00:25:B5:02:00:09"
    - map_order: "sequential"
    - map_org_dn: "{{ ucs_site_dn }}"
    - state: "{{ deployment_state}}"

  # Create BIOS Policy for HPC
  - include_tasks: task-CreateBIOsPolicy.yaml

  # Create User Ack Maintenance Policy
  - include_tasks: task-CreateMaintenancePolicy.yaml

  # Create Local Disk Configuration Policies
  - include_tasks: task-CreateLocalDiskConfigPolicy.yaml

