---

- name: HPC Template
  gather_facts: no
  connection: local
  hosts: ucsm
  vars:
    - ucs_site_name: TestSite
    - ucs_site_description: Test Site for Ansible Demonstration
    - deployment_state: present
    - mac_pool_name:

  tasks:
  - name: "Create Site {{ ucs_site_name  }}"
    include_tasks: task-ConfigureSite.yaml

  - include_tasks: task-CreateSystemVLANs.yaml
    vars:
    # List of VLANS to be created on the Fabric Interconnects
    - vlans:
        mgmtVlan:
         id: "50"
         fabric: "common"
         native: "no"
         sharing: "none"
  
  # One VNIC Template for LINUX Host with failover
  - include_tasks: task-CreateVNIC.yaml
    vars:
    - vlans:
        mgmtVlan:
          native: "yes"
    - vnic_fabric: "A-B"
    - vnic_mtu: "1500"
    - vnic_name: "eth0"
    - vnic_redundancy_type: "none"
    - vnic_template_type: "updating-template"
    - vnic_org_dn: "org-root/org-{{ ucs_site_name }}"
         


