---

  - name: Create System VLANS
    ucs_vlans:
      hostname: "{{ ucsm_host }}"
      username: "{{ ucsm_user }}"
      password: "{{ ucsm_password }}"
      fabric: "{{ item.value.fabric }}"
      id: "{{ item.value.id }}"
      name: "{{ item.key }}"
      native: "{{ item.value.native }}"
      sharing: "{{ item.value.sharing }}"
      state: "{{ deployment_state }}"
    with_dict: "{{ vlans }}"
        
