---

  - name: BIOs Policy
    ucs_managed_objects:
      hostname: "{{ ucsm_host }}"
      username: "{{ ucsm_user }}"
      password: "{{ ucsm_password }}"
      objects:
      - module: ucsmsdk.mometa.bios.BiosVProfile
        class: BiosVProfile
        properties:
          parent_mo_or_dn:  "{{ ucs_site_dn }}"
          name: "{{ ucs_bios_policy_name }}"
        children:
          - module: ucsmsdk.mometa.bios.BiosVfEnhancedIntelSpeedStepTech
            class: BiosVfEnhancedIntelSpeedStepTech
            properties:
              vp_enhanced_intel_speed_step_tech: enabled
          - module: ucsmsdk.mometa.bios.BiosVfIntelHyperThreadingTech
            class: BiosVfIntelHyperThreadingTech
            properties:
              vp_intel_hyper_threading_tech: disabled
          - module: ucsmsdk.mometa.bios.BiosVfIntelVirtualizationTechnology 
            class: BiosVfIntelVirtualizationTechnology 
            properties:
              vp_intel_virtualization_technology: disabled
          - module: ucsmsdk.mometa.bios.BiosVfIntelVTForDirectedIO
            class: BiosVfIntelVTForDirectedIO
            properties:
              vp_intel_vt_for_directed_io: disabled
          - module: ucsmsdk.mometa.bios.BiosVfCPUPerformance
            class: BiosVfCPUPerformance
            properties:
              vp_cpu_performance: "enterprise"
          - module: ucsmsdk.mometa.bios.BiosVfDirectCacheAccess
            class: BiosVfDirectCacheAccess
            properties: 
              vp_direct_cache_access: enabled
          - module: ucsmsdk.mometa.bios.BiosVfProcessorEnergyConfiguration
            class: BiosVfProcessorEnergyConfiguration
            properties:
              vp_energy_performance: energy-efficient
          - module: ucsmsdk.mometa.bios.BiosVfIntelTurboBoostTech
            class: BiosVfIntelTurboBoostTech
            properties:
              vp_intel_turbo_boost_tech: enabled
          - module: ucsmsdk.mometa.bios.BiosVfPSTATECoordination
            class: BiosVfPSTATECoordination
            properties:
              vp_pstate_coordination: "hw-all"
          - module: ucsmsdk.mometa.bios.BiosVfProcessorEnergyConfiguration
            class: BiosVfProcessorEnergyConfiguration
            properties:
              vp_power_technology: "performance"
          - module: ucsmsdk.mometa.bios.BiosVfProcessorCState
            class: BiosVfProcessorCState
            properties:
              vp_processor_c_state: enabled
          - module: ucsmsdk.mometa.bios.BiosVfProcessorC1E
            class: BiosVfProcessorC1E
            properties:
              vp_processor_c1_e: enabled
          - module: ucsmsdk.mometa.bios.BiosVfProcessorC3Report
            class: BiosVfProcessorC3Report
            properties:
              vp_processor_c3_report: enabled
          - module: ucsmsdk.mometa.bios.BiosVfProcessorC6Report
            class: BiosVfProcessorC6Report
            properties:
              vp_processor_c6_report: enabled
          - module: ucsmsdk.mometa.bios.BiosVfProcessorC7Report
            class: BiosVfProcessorC7Report
            properties:
              vp_processor_c7_report: enabled
          - module: ucsmsdk.mometa.bios.BiosVfPackageCStateLimit
            class: BiosVfPackageCStateLimit
            properties:
              vp_package_c_state_limit: "no-limit"
          - module: ucsmsdk.mometa.bios.BiosVfEnergyPerformanceTuning
            class: BiosVfEnergyPerformanceTuning
            properties:
              vp_pwr_perf_tuning: "os"
          - module: ucsmsdk.mometa.bios.BiosVfCPUHardwarePowerManagement
            class: BiosVfCPUHardwarePowerManagement
            properties:
              vp_cpu_hardware_power_management: "hwpm-native-mode"
          - module: ucsmsdk.mometa.bios.BiosVfWorkloadConfiguration
            class: BiosVfWorkloadConfiguration
            properties:
              vp_workload_configuration: "balanced"
          - module: ucsmsdk.mometa.bios.BiosVfNUMAOptimized
            class: BiosVfNUMAOptimized
            properties:
              vp_numa_optimized: enabled
          - module: ucsmsdk.mometa.bios.BiosVfSelectMemoryRASConfiguration
            class: BiosVfSelectMemoryRASConfiguration
            properties:
              vp_select_memory_ras_configuration: "maximum-performance"
