---

  - name: Create vNIC Templates
    ucs_vnic_template:
      hostname: "{{ ucsm_host }}"
      username: "{{ ucsm_user }}"
      password: "{{ ucsm_password }}"
      name: "{{ vnic_name }}"
      fabric: "{{ vnic_fabric }}"
      mac_pool: "{{ mac_pool_name }}"
      mtu: "{{ vnic_mtu }}"
      state: "{{ deployment_state }}"
      redundancy_type: "{{ vnic_redundancy_type }}"
      template_type: "{{ vnic_template_type }}"
      org_dn: "{{ vnic_org_dn }}"
      vlans_list:
      - name: "{{ item.key }}"
        native: "{{  item.value.native }}"
        state: "{{ deployment_state }}"
    with_dict: "{{ vlans }}"
