---

  - name: BIOs Policy
    ucs_managed_objects:
      hostname: "{{ ucsm_host }}"
      username: "{{ ucsm_user }}"
      password: "{{ ucsm_password }}"
      objects:
      - module: ucsmsdk.mometa.bios.BiosVProfile
        class: BiosVProfile
        properties:
          parent_mo_or_dn:  "{{ ucs_site_dn }}"
          name: "{{ ucs_bios_policy_name }}"
        children:
          - module: ucsmsdk.mometa.bios.BiosVfEnhancedIntelSpeedStepTech
            class: BiosVfEnhancedIntelSpeedStepTech
            properties:
              vp_enhanced_intel_speed_step_tech: enabled
          - module: ucsmsdk.mometa.bios.BiosVfIntelHyperThreadingTech
            class: BiosVfIntelHyperThreadingTech
            properties:
              vp_intel_hyper_threading_tech: disabled
          - module: ucsmsdk.mometa.bios.BiosVfIntelVirtualizationTechnology 
            class: BiosVfIntelVirtualizationTechnology 
            properties:
              vp_intel_virtualization_technology: disabled
          - module: ucsmsdk.mometa.bios.BiosVfIntelVTForDirectedIO
            class: BiosVfIntelVTForDirectedIO
            properties:
              vp_intel_vt_for_directed_io: disabled
          - module: ucsmsdk.mometa.bios.BiosVfCPUPerformance
            class: BiosVfCPUPerformance
            properties:
              vp_cpu_performance: "enterprise"
          - module: ucsmsdk.mometa.bios.BiosVfDirectCacheAccess
            class: BiosVfDirectCacheAccess
            properties: 
              vp_direct_cache_access: enabled
          - module: ucsmsdk.mometa.bios.BiosVfProcessorEnergyConfiguration
            class: BiosVfProcessorEnergyConfiguration
            properties:
              vp_energy_performance: energy-efficient
          - module: ucsmsdk.mometa.bios.BiosVfIntelTurboBoostTech
            class: BiosVfIntelTurboBoostTech
            properties:
              vp_intel_turbo_boost_tech: enabled
          - module: ucsmsdk.mometa.bios.BiosVfPSTATECoordination
            class: BiosVfPSTATECoordination
            properties:
              vp_pstate_coordination: "hw-all"
