---

- name: Configure C Series Servers in inventory file
  gather_facts: no
  connection: local
  hosts: Lab_C240_M5
  tasks:
  - import_tasks: tasks/task-PowerOnServer.yaml
  - import_tasks: tasks/task-ConfigureNTP.yaml
  - import_tasks: tasks/task-ConfigureEmailAlert.yaml
  - import_tasks: tasks/task-ConfigureBootOrder.yaml
  - import_tasks: tasks/task-ConfigureBios.yaml
  - import_tasks: tasks/task-ConfigureVIC.yaml
