---

    - name: Power Off the Server through XML API
      imc_rest:
        hostname: '{{imc_host}}'
        username: '{{imc_user}}'
        password: '{{imc_password}}'
        validate_certs: no
        content: |
          <configConfMo><inConfig>
          <computeRackUnit dn="sys/rack-unit-1" adminPower="soft-shut-down"/>
          </inConfig></configConfMo>

    - name: Pause for server to shutdown
      pause:
        seconds: 20

