---
    - name: Configure vMedia
      imc_rest:
        hostname: '{{imc_host}}'
        username: '{{imc_user}}'
        password: '{{imc_password}}'
        validate_certs: no
        content: |
          <configConfMo dn="sys/huu/firmwareUpdater"><inConfig>
          <huuFirmwareUpdater 
          remoteIp="{{ firmware_ip }}" 
          remoteShare="{{ firmware_path }}{{ firmware_file }}" 
          mapType="{{ firmware_map }}" 
          stopOnError='yes' 
          timeOut='120' 
          verifyUpdate='yes' 
          updateComponent='all,hdd' 
          updateType='immediate' 
          doForceDown='yes' 
          skipMemoryTest="Enabled" 
          gracefulTimeout='3' 
          bootMedium="vmedia" adminState="trigger" />
          </inConfig></configConfMo>